### ISSUE TITLE
show school location in the map from the ordered schools list

### ISSUE THREAD

**Issue by visancal** [decasaalcole/decasaalcole-web#20]

**Comment by raolbaletco** [comment]
First Version 
Table of Equivalence for the schools list
Link: https://www.dropbox.com/s/gq762rmlrz8ll4n/Datos_Cole.ods?dl=0 

nived_desc  nived
COL·LEGI D'EDUCACIÓ INFANTIL      A
CENTRE PRIVAT D'EDUCACIÓ INFA      A
CENTRE PRIVAT E. INFANTIL, PRI  AC
INSTITUT D'EDUCACIÓ SECUNDÀR      DE
ESCOLA PRIVADA DE MÚSICA           G
ESCOLA INFANTIL DE PRIMER CICL  A
COLEGIO DE EDUCACIÓN INFANTIL      A
C. DOCENT PÚB. DE FORMACIÓ B      H
CENTRE PRIVAT FORMACIÓ PROFES      F
CENTRE PÚBLIC DE FORMACIÓ DE      H
ESCUELA PRIVADA DE MÚSICA          G
INSTITUTO DE EDUCACIÓN SECUND      DE
ESCUELA INFANTIL DE PRIMER CIC  A
CONSERVATORI PROFESSIONAL DE M  G
C. DOCEN. PÚB. DE FORMACIÓN       H
CENTRE DOCENT PRIVAT ESTRANGER  H
CENTRE AUTORITZAT D'ENSENYANCE  H
CENTRE PRIVAT E. INFANTIL I PR  AC
COL·LEGI RURAL AGRUPAT             AC
CENTRE D'EDUCACIÓ ESPECIAL         B
CENTRE AUTORITZAT ELEMENTAL DE  G
CENTRE PRIVAT E. PRIMÀRIA I S      CDE
CENTRO PRIVADO E. INFANTIL, PR  AC
SECCIÓ D'EDUCACIÓ SECUNDÀRI      DE
CENTRE PRIVAT D'EDUCACIÓ ESPE      B
COLEGIO RURAL AGRUPADO          AC
CENTRE PRIVAT D'EDUCACIÓ SECU      DE
CENTRO PÚBLICO DE FORMACIÓN       F
CENTRE INTEGRAT PÚBLIC DE FOR      F
ESCOLA INFANTIL                 A
ESCOLA OFICIAL D'IDIOMES        I
ESCOLA PÚBLICA DE MÚSICA          G
CONSERVATORIO PROFESIONAL DE M  G
COL·LEGI D'EDUCACIÓ PRIMÀRI      C
ESCOLA PRIVADA DE MÚSICA I DA      G
ESCUELA PÚBLICA DE MÚSICA         G
SECCIÓN DE EDUCACIÓN SECUNDA      DE
CENTRO PRIVADO DE EDUCACIÓN I      A
CONSERVATORI ELEMENTAL DE MÚS      G
CENTRE AUTORITZAT D'ENSENYAMEN  J
CENTRE PRIVAT DE PÀRVULS           A
ESCUELA OFICIAL DE IDIOMAS      I
CONSERVATORI PROFESSIONAL DE D  G
ESCUELA INFANTIL                A
COLEGIO DE EDUCACIÓN PRIMARIA      C
ESCOLA D'ART I SUPERIOR DE DIS  H
ESCOLA PÚBLICA DE MÚSICA I D      G
CENTRE PRIVAT DE PREESCOLAR     A
CENTRO PRIVADO FORMACIÓN  PRO      F
ESCOLA PRIVADA DE DANSA         G
CENTRE INTEGRAT DE MÚSICA I E      G
CENTRO DE EDUCACIÓN ESPECIAL       B
CONSERVATORI ELEMENTAL DE DANS  G
CONSERVATORI SUPERIOR DE MÚSI      G
C. DOCENT PRV. DE FORMACIÓ BC      H
CENTRO PRIVADO DE EDUCACIÓN E      B
CENTRO PRIVADO DE EDUCACIÓN S      D
CENTRE PRIVAT DE PÁRVULS I PR      AC
C. DOCENT PRV. DE FORMACIÓ BA      H
CONSERVATORI SUPERIOR DE DANSA  G
CENTRO DOCENTE PRIVADO EXTRANJ  H
CENTRE PRIVAT DE FORMACIO DE P  F
ESCUELA PÚBLICA DE DANZA           G
ESCOLA LLAR                     CD
CENTRO INTEGRADO PÚBLICO DE F      F
CENTRO PRIVADO E. INFANTIL Y P  AC
CENTRE PRIVAT DE PREESCOLAR I   AC
CENTRE PRIVAT E. INFANTIL I SE  ACD
ESCOLA SUPERIOR D'ART DRAMÀTI      H
CENTRE PRIVAT DE JARDÍ D'INFS      A
ESCUELA DE VITICULTURA Y ENOLO  H
CENTRE AUT. D'ENSENYANCES ARTB  H
ESCUELA PRIVADA DE MÚSICA Y D      G
CENTRO PRIVADO E. PRIMARIA Y S  CDE
CENTRE PÚBLIC INTEGRAT             J
ESCUELA PRIVADA DE DANZA        G
ESCOLA SUPERIOR DE CERÀMICA        H
CENTRE PÚBLIC EDUCACIÓ A DIS      DEFI
ESCOLA DE CAPACITACIÓ AGRÀRI      H
ESCUELA DE ARTE Y SUPERIOR DE   H
ESCOLA D'ART I SUPERIOR DE CER  H
CENTRO PRIVADO DE PREESCOLAR    A
ESCOLA EUROPEA                  ACDE
.                               H

**Comment by visancal** [comment]
Done but appers the map size bug

**Comment by visancal** [comment]
Done
