### ISSUE TITLE
Pad schools ids on links

### ISSUE THREAD

**Issue by jsanz** [decasaalcole/decasaalcole-web#25]
Schools ids are not padded so for example instead of this link

http://www.cece.gva.es/ocd/areacd/es/centro.asp?codi=03015981

The application is linking to this url

http://www.cece.gva.es/ocd/areacd/es/centro.asp?codi=3015981

Maybe the school ids on the database should be strings instead of numbers???

**Comment by vehrka** [comment]
They should have been strings from the beginning...

Please remember that if you are not going to perform mathematical
operations with the data it shouldn't be stored in numerical types.

Pedro-Juan Ferrer Matoses
En movimiento

**Comment by visancal** [comment]
Done
